* [32mRodrigo                 [m 3f03abf added scoring in mapActivity
  UI_UPDATE               [m 46d6984 Update
  YM                      [m 46635d8 [ahead 1] fixed gradle stuff
  master                  [m 216149a add README
  [31mremotes/origin/HEAD     [m -> origin/master
  [31mremotes/origin/Rodrigo  [m 3f03abf added scoring in mapActivity
  [31mremotes/origin/UI_UPDATE[m 46d6984 Update
  [31mremotes/origin/YM       [m a267966 Firebase Updated
  [31mremotes/origin/master   [m 216149a add README
